Test with Bundler v1 and v2 (#54)
* Test with Bundler v1 and v2

* Allow any bundler version

* Don't fail fast

We want the full picture of all elements of the matrix.

* Install matching version of bundler

* Bundler needs a Pathname here

Otherwise errors like:

```
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.11/lib/bundler/source/path.rb:29:in `initialize': undefined method `expand_path' for "/tmp/d20210224-2294-13e1bm3":String (NoMethodError)
       +	from /home/runner/work/cobra_commander/cobra_commander/lib/cobra_commander/dependencies/bundler.rb:37:in `new'
       +	from /home/runner/work/cobra_commander/cobra_commander/lib/cobra_commander/dependencies/bundler.rb:37:in `components_source'
       +	from /home/runner/work/cobra_commander/cobra_commander/lib/cobra_commander/dependencies/bundler.rb:23:in `components'
       +	from /home/runner/work/cobra_commander/cobra_commander/lib/cobra_commander/umbrella.rb:32:in `add_source'
```

Seems to have been caused by https://github.com/rubygems/rubygems/commit/fc843c1ebca35249db76eb664e7015543d6d5046